### ISSUE TITLE
Solid blocks do not block light

### ISSUE THREAD

**Issue by MaxLegend** [elytra/Albedo#23]
After I created the block and tile entity for my mod, I turned on the luminosity in different colors using this library. Unfortunately, for some reason, if you close the light source with solid blocks on all sides, it still shines brightly through the blocks. I thought for a long time, but never came up with how to solve this problem. I will be glad to help.
If this error cannot be fixed, nobody needs the library at all. This is a serious graphic error, I believe.
I am using minecraft version 1.12.2

**Comment by falkreon** [comment]
Mirage is for cosmetic lighting - it works so well and so quickly because it does not interact with the Minecraft lighting engine at all. No steps will be taken to calculate occlusions. That would be a completely different mod.

**Comment by MaxLegend** [comment]
But in this case, the mod is absolutely useless and does not make sense?
Is that hard to do? Can you make such a mod?

**Comment by falkreon** [comment]
Back in the day TheMogMiner and CptSpaceToaster put together different implementations to stuff colored light data into Minecraft's own light-level data - https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/wip-mods/1445251-1-7-10-beta-wip-colored-light-progress-and

This isn't a particularly slow idea, it could certainly be done well and fast, and there's no reason Mojang can't do this themselves. But since they didn't, and since the lighting engine receives significant updates each version, writing a mod that alters the lighting system is bound to require heavy maintenance for every single release. It also requires deep changes that would be easier in fabric mixin than in forge asm, but hard enough that only certain modders could pull it off. That's my guess as to why I don't see any colored lights at all which is currently maintained.

As for what the use-cases are for *this* mod (which, I've worked with the team maintaining Albedo to fold my innovations back into their mod, which is the one you should use if they get a release done), are things like transient spell effects, magic fireflies, things like that which are more visual feedback and atmosphere than mechanical. These things don't matter so much if there's effect bleed through a wall.
