### ISSUE TITLE
Move to a Capability

### ISSUE THREAD

**Issue by Darkhax** [elytra/Albedo#3]
This would allow mods to support lights for tiles and entities without having to have direct access to the tile/entity class code. Useful for add-ons and wrappers.

**Comment by asiekierka** [comment]
hasCapability + getCapability is much slower than interfaceof *and* cannot be cached, which implies iterating all entities and tile entities on the client side at least twenty times a second will become much slower. I vote against. Use GatherLightsEvent.

**Comment by Darkhax** [comment]
Ah, you're right. Didn't think about it like that.

**Comment by malte0811** [comment]
I think [this](https://github.com/MinecraftForge/MinecraftForge/pull/4174#issuecomment-314991496) comment by Lex is relevant here. He seems to want to remove @Optional (which is the only way of adding compat that I know of (without Albedo as a hard dependency)), with only capabilities as a replacement. I assume that @asiekierka is right but I can't run any tests to show it until Tuesday, otherwise I'd put a comment with test results on the PR I linked.

**Comment by exaskye** [comment]
Ugh. If Lex does remove Optional, I suppose we'll have no choice but to move to caps, but as it stands I'm not adding a cap.

**Comment by asiekierka** [comment]
If Lex removes Optional, just add a contract to ILightProvider stating that you can't just change the interface whenever you want, and then bind TileEntities/Entities to them and check the validity of those?
